### ISSUE TITLE
為什麼我們不常用 command module？

### ISSUE THREAD

**Issue by chusiang** [ansible-tw/AMA#10]
[`command`](http://docs.ansible.com/ansible/command_module.html) module 很好用很方便，但您會發現別人的 Ansible Playbook 裡很少會使用它，這是為什麼呢？

**Comment by chusiang** [comment]
1. 我們會儘可能的使用現成的 Modules，非必要才會使用 command module。用了它我們得自己處理**重複執行**的問題，有時還會拖累整體的效率。
1. 如果有一個特定目標，要用到很多的 tasks，這時我們會建議使用 roles。
1. 在很多需要較複雜運算的狀況我們會改用 shell 或 script module。

**Comment by aweimeow** [comment]
在嘗試 script module 之後，我將我要做的所有事情寫成一隻 Shell Script。

而我想做的是嘗試自動安裝一個名為 `onos` 的軟體。

在這邊提供關於使用 `script module` 去呼叫 Shell Script 的方法：
```bash
- name: Install ONOS and start ONOS instance
  hosts: sdn
  tasks: 
    - name: Install needed command from apt
      apt: 
        name: {{item}} state=installed
        with_items: 
          - git
          - curl
          - unzip
          - zip

    - name: Clone ONOS from git
      git: 
        repo: https://gerrit.onosproject.org/onos
        dest: /root/onos
        clone: yes
        version: master

    - name: Install onos by script
      script: scripts/onos.sh
```

在安裝 script 的時候有個值得一提的事情，在安裝 Java 8 的時候，會出現這個畫面：
![](https://i.imgur.com/sFstKR3.png)

然而，要透過 Shell Script 來敲下 OK 卻讓我不知所措 ... XD

我有嘗試過：
```
yes | apt-get install oracle-java8-installer oracle-java8-set-default -y # 一直把 yes 輸進去
echo "\nyes" | apt-get install oracle-java8-installer oracle-java8-set-default -y # 模擬敲下 Enter 再輸入 Yes
# 連 printf 都有試過了 XD
```

不過都解不了，後來在[這個討論串](http://askubuntu.com/questions/190582/installing-java-automatically-with-silent-option)找到解決辦法，如以下所示：
```
echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | sudo debconf-set-selections
apt-get install oracle-java8-installer oracle-java8-set-default -y
```

這樣就成功 PASS  過去那個 Prompt 了。

**Comment by chusiang** [comment]
@aweimeow 或許您可以試著改用 debconf module 來解這一題。:)

- http://docs.ansible.com/ansible/debconf_module.html

**Comment by aweimeow** [comment]
原來如此！受教了 <(_ _)>
