### ISSUE TITLE
如何透過 Ansible 修改主機 sudoers 規則

### ISSUE THREAD

**Issue by Ichiro-Hu** [ansible-tw/AMA#12]
我的需求：在有數十台 Linux 系統主機管理需求下，即使能夠自動化創立 user account，但 sudo 權限要如何做好基本管理呢？
我的環境：CentOS 6 / 7 版
我的 LAB 環境：vagrant centos7

1. 首先我先建立基於 Ops 群組的 sudo 規則。

       - name: Allow 'Ops' group to have passwordless sudo
         lineinfile:
           create: yes
           dest: /etc/sudoers.d/ops
           state: present
           line: '%Ops    ALL=(ALL)       NOPASSWD: ALL, !NO_SHELL'
           validate: 'visudo -cf %s'

lab 發現：一開始我也是透過 lineinfile 方式去異動 sudoers 主檔案，但在重複執行相同 playbook.yml 情形下，會造成多筆重複規則，故改成 create 模式去建立此群組 sudo規則，就不會發生重複建立規則了。

2. 接著建立上述規則中的 NO_SHELL 參數內容。

       - name: Add Cmnd_Alias sudo shell
         lineinfile:
           dest: /etc/sudoers
           state: present
           regexp: '^## Drivers'
           line: 'Cmnd_Alias NO_SHELL = /bin/su, /bin/sudo, /bin/passwd, /bin/passwd root, /sbin/visudo, /sbin/sysctl -w *, /bin/* /etc/sudoers, /bin/rm -rf * --no-preserve-root'
           validate: 'visudo -cf %s'

lab 發現：valiidate 參數是非常重要的，沒此參數是很容易造成 sudo 權限炸了，於真實系統環境中是不被允許的。經由 validate 參數幫你驗證 sudo規 則是否可被系統接受，是有必要的。

舉例 1（有 validate 真好）：
vagreant centos 環境中無 userdel 指令，如在上述規則中包含此指令，在執行 playbook 時會出現：`syntax error near line 47` ; 執行錯誤沒關係，查原因後再改規則就好。

舉例 2（沒 validate 真糟）：
如沒有 validate 參數，即使 sudo 規則是可被接受的，但如不小心重複執行相同 playbook，則 ..... sudo 權限立刻炸了～～

所以此 LAB 的重要心得是：validate 參數非常重要、透過 ansible 去修改 sudoers 規則是安全可行的。

**Comment by chusiang** [comment]
Thank you for @Ichiro-Hu .

順帶一提：我在《Ansible: Up and Running》一書的 167 頁也有看到 `validate` 的相關範例，但還沒實際用過就是。:P
