### ISSUE TITLE
Ansible的超时控制

### ISSUE THREAD

**Issue by jackpgao** [ansible-tw/AMA#16]
Ansible自带的超市机制，在一些特殊情况下，无法有效超时，这个问题有人遇到过么？

如果是用外部程序来进行超时处理，那Ansible自带的并发还有什么意义？我就需要在外部程序调用的时候控制超时和并发了。

**Comment by theqwan-chengwei** [comment]
嗨，也許你可以將問題再描述得更仔細一點，像是你所謂的特殊狀況為何？
以及為何你會覺得 Ansible 自帶的併發沒有意義，這樣其他人比較能看懂你想要問重點是什麼，
另外為了建立共識，你所謂的超時，是指 timeout 嗎？
自帶的併發指的是 ansible.cfg 中的 forks 嗎？
http://docs.ansible.com/ansible/intro_configuration.html#forks

最後，即便不討論 Ansible 本身，其實你要怎麼使用工具是一件很彈性的事情，如果你覺得 Ansible 原生的功能不好用，你可以送 PR 貢獻，或是如你說的自己用外部程序來克服困難，這都是大家常見的作法。

**Comment by chusiang** [comment]
Hi @jackpgao 

如果是 timeout 的部份，或許 https://github.com/ansible-tw/AMA/issues/2 討論的  `async` 和 `poll` 可以幫得上您的忙。:P

**Comment by chusiang** [comment]
看來暫時沒有後續的討論？我就先關 issue，之後有後續再 repoen 吧！
