### ISSUE TITLE
若 tasks 中包含 reboot 動作，如何在 reboot 之後，還能接續執行 tasks？

### ISSUE THREAD

**Issue by theqwan-chengwei** [ansible-tw/AMA#2]
以下即為一個範例答案：

```
- name: Reboot Server
  command: /usr/sbin/reboot
  async: 1
  poll: 0
  ignore_errors: true

- name: Wait for the server to finish rebooting
  become: false
  local_action: wait_for host="{{ansible_hostname | default(inventory_hostname)}}" delay=30 timeout=300

# 其中 wait_for 的 `timeout` 預設值即是 300，因此如果不想等這麼久，記得自己要改短一點。
```

更多細節可以參考官方文件 [Module - wait_for](http://docs.ansible.com/ansible/wait_for_module.html)
以及[這篇文件的 Delegation 這一段落](http://docs.ansible.com/ansible/playbooks_delegation.html)，內有幾個案例提到 `local_action`。

另外補充，在 tasks `Reboot Server` 的 `async` 與 `poll` 是什麼意思呢？

請參閱官方文件 [《Asynchronous Actions and Polling》](http://docs.ansible.com/ansible/playbooks_async.html)，

```
- name: simulate long running op (15 sec), wait for up to 45 sec, poll every 5 sec
  command: /bin/sleep 15
  async: 45
  poll: 5
```

用上面的官方案例來說明，即是「等待 45 秒，每 5 秒輪詢一次」。

所以最前面的案例，將它用在 tasks `Reboot Server` 即是為了用來幫助我們確認是否有確實完成 reboot 動作，因為如果你閒置太久會被中斷 SSH 連線，因此如果有需要長時間等待的動作都可應用此技巧。

另外要注意 poll 預設值是 10 秒，因此不夠用或不需要等待這麼久，記得要自己另外設定。

**Comment by chusiang** [comment]
話說在下先前研究 Windows Support 時，在使用 `win_reboot` module 時也有用過 `wait_for`，印象中 winrm 要有自動啟用才可接續做下個 task。
