### ISSUE TITLE
How to show color on GitLab CI ?

### ISSUE THREAD

**Issue by chusiang** [ansible-tw/AMA#24]
1. I want to use **color mode** to play the ansible playbooks **on GitLab CI**, but default is not. 

    > https://gitlab.com/chusiang/helloworld.ansible.role/-/jobs/21539273

   ![Run the Ansible with GitLab CI (no color)](https://user-images.githubusercontent.com/219066/27966690-be6a31d2-6372-11e7-8f46-9f8eecf754be.png)

1. I find the `force_color` configure, when we set to `1`, it could be use the color mode.  

   ```cfg
   $ vim ansible.cfg
   [defaults]
   
   force_color = 1
   ```

1. Done.

    > https://gitlab.com/chusiang/helloworld.ansible.role/-/jobs/21538921

   ![screen shot 2017-07-08 at 00 16 32](https://user-images.githubusercontent.com/219066/27966768-08f9aafc-6373-11e7-9bd9-e1a5d1d99426.png)

Enjoy it !

## Reference

- 《Ansible: Up and Running》by Lorin Hochstein

chusiang
2017.07.08

**Comment by chusiang** [comment]
無心插柳柳成陰，隨意翻翻《Ansible: Up and Running》一書，卻不小心解了敝人多時的疑惑。 :stuck_out_tongue_closed_eyes:

**Comment by usego** [comment]
That works, thanks!

**Comment by tomas223** [comment]
This didn't work for me. What helped was adding
```yaml
  variables:
    ANSIBLE_FORCE_COLOR: 'true'
```
to ci job.

**Comment by chusiang** [comment]
Hi @tomas223 ,

Please add the `force_color = 1` line into the `ansible.cfg`, not playbook.

> https://github.com/ansible-tw/AMA/issues/24#issue-241314016

**Comment by tsengeagle** [comment]
這邊設定
![圖片](https://user-images.githubusercontent.com/6193596/60415983-4f46e700-9c0f-11e9-91d3-53d8bf2f6dca.png)

ci console
![圖片](https://user-images.githubusercontent.com/6193596/60416045-76051d80-9c0f-11e9-8953-23fd0cf47fdc.png)
