### ISSUE TITLE
是否有建議看的文章, 有關 Jenkins 跟 ansible 怎麼合用?

### ISSUE THREAD

**Issue by mingderwang** [ansible-tw/AMA#3]

**Comment by chusiang** [comment]
Jenkins 的話，搭配 [Ansible Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Ansible+Plugin) 應該就很好用了吧？:P

不然就等 @tsoliangwu0130 把《30 天入門 Ansible 及 Jenkins-CI》給寫完吧！

> http://ithelp.ithome.com.tw/ironman/signup/list?group=devops

**Comment by mingderwang** [comment]
@chusiang  謝謝, 我直接裝 Ansible Plugin 來試試.
