### ISSUE TITLE
請問怎麼讀取 hostvars 裡面的值？

### ISSUE THREAD

**Issue by changchichung** [ansible-tw/AMA#34]
我在研究怎麼抓hostvars裡面的某些變數值來應用，可是一直沒成功
playbook內容就只有
```
- hosts: all
  become: True
  become_method: sudo

  tasks:
    - debug: 
       var: "{{ hostvars[groups]}} " 
```
我想要讀取 hostvars 中的 groups 這個值

底下是用 debug: var="{{ hostvars }}" 跑出來的部份內容
```
ok: [dc075.abc] => {
    "hostvars[inventory_hostname]": {
        "admin_user": "minion",
        "admin_user_uid": 1001,
        "admin_users": [
            {
                "comment": "{{ admin_user }}",
                "name": "{{ admin_user }}",
                "uid": "{{ admin_user_uid }}"
            },
            {
                "comment": "{{ server_admin_user }}",
                "name": "{{ server_admin_user }}",
                "uid": "{{ server_admin_user_uid }}"
            },
            {
                "comment": "{{ client_admin_user }}",
                "name": "{{ client_admin_user }}",
                "uid": "{{ client_admin_user_uid }}"
            },
            {
                "comment": "{{ network_admin_user }}",
                "name": "{{ network_admin_user }}",
                "uid": "{{ network_admin_user_uid }}"
            }
        ],
        "ansible_all_ipv4_addresses": [
            "192.168.11.75"
        ],
        "ansible_all_ipv6_addresses": [
            "fe80::826e:1b84:3cbf:2063"
        ],
        "ansible_apparmor": {
            "status": "enabled"
        },
        "ansible_architecture": "x86_64",
        "ansible_bios_date": "07/04/2018",
        "ansible_bios_version": "N1QET77W (1.52 )",
        "ansible_check_mode": false,
        "ansible_cmdline": {
            "BOOT_IMAGE": "/@/boot/vmlinuz-4.15.0-38-generic",
            "quiet": true,
            "ro": true,
            "root": "UUID=667ba7bc-42b6-496b-9737-043a2718e6a7",
            "rootflags": "subvol=@",
            "splash": true,
            "vt.handoff": "1"
        },
        "groups": {
                "accountservers": [
                    "s009.abc.om"
                ],
                "administrationservers": [
                    "s010.abc.om"
                ],
                "all": [
                    "s220.abc.om",
                    "s007.abc.om",
                    "s021.abc.om",
                    "s014.abc.om"
                ],
                "branchservers": [
                    "192.168.80.7",
                    "192.168.80.10",
                    "192.168.28.30",
                    "192.168.28.7"
                ],
                "buildservers": [
                    "s007.abc.om"
                ],
                "clients": [
                    "dc075.abc.om",
                    "dc076.abc.om",
                    "dc077.abc.om",
                    "dc023.abc.om"
                ],
                "developerclients": [
                    "dc039.abc.om",
                    "dc078.abc.om",
                    "dc075.abc.om",
                    "dc076.abc.om",
                    "dc077.abc.om"
                ],
                "dockerservers": [
                    "s067.abc.om",
                    "s013.abc.om"
                ],
                "fileservers": [
                    "s006.abc.om"
                ],
                "kvmservers": [
                    "s161.abc.om"
                ],
                "machines": [
                    "192.168.70.10",
                    "192.168.80.30",
                    "192.168.80.6",
                    "192.168.80.7",
                    "192.168.80.10",
                    "192.168.28.30",
                    "192.168.28.7",
                    "s220.abc.om",
                    "s007.abc.om",
                    "s021.abc.om",
                    "s014.abc.om"
                ],
                "mailservers": [
                    "s220.abc.om"
                ],
                "miscservers": [
                    "s235.abc.om",
                    "s236.abc.om"
                ],
                "monitorservers": [
                    "s017.abc.om"
                ],
                "neonexusapservers": [
                    "s021.abc.om",
                    "s014.abc.om"
                ],
                "neonexusdbservers": [
                    "s022.abc.om",
                    "s015.abc.om"
                ],
                "nexusservers": [
                    "s120.abc.om",
                    "s119.abc.om",
                    "s05.abc.om",
                    "s003.abc.om",
                    "s020.abc.om",
                    "s019.abc.om",
                    "s121.abc.om",
                    "s223.abc.om"
                ],
                "ostservers": [
                    "s221.abc.om"
                ],
                "rproxyserver": [
                    "s058.abc.om"
                ],
                "servers": [
                    "s010.abc.om",
                    "s022.abc.om",
                    "s015.abc.om",
                    "s161.abc.om"
                ],
                "ungrouped": [],
                "userclients": [
                    "dc023.abc.om"
                ]
```
我本來的想法是判斷當這台電腦的hostname 有出現在 groups中 就去作動作
但是一直抓不到 groups 來判斷...

請問我應該要怎麼正確讀取hostvars 裡面的任一個變數的值？

**Comment by chusiang** [comment]
現在有些晚了，明早開完會，再來仔細觀看這個問題哩。😅

**Comment by linzeyan** [comment]
應該是 hostvars[inventory_hostname]['groups'] 吧

**Comment by tsengeagle** [comment]
像這樣嗎？

抓portal這個群組

`ansible apl01 -i inventories/tp-intt -m debug -a "msg={{ hostvars[inventory_hostname].groups.portal }}"`

![default](https://user-images.githubusercontent.com/6193596/48386122-e49e7500-e72b-11e8-8971-49834ce5e485.png)

![default](https://user-images.githubusercontent.com/6193596/48386110-dc463a00-e72b-11e8-88f3-4564f72a5fe8.png)

**Comment by zarr12steven** [comment]
@changchichung 

https://docs.ansible.com/ansible/2.5/user_guide/playbooks_conditionals.html

這裡面應該會有你要的答案。

**Comment by changchichung** [comment]
> `ansible apl01 -i inventories/tp-intt -m debug -a "msg={{ hostvars[inventory_hostname].groups.portal }}"`

是的，我的疑問是
1. 為何用 msg 可以，但是用 var 就會出錯？
2. 我要如何得知要用 "hostvars[inventory_hostname]" .groups.portal 這種格式，為什麼不是用 hostvars.inventory_hostname.groups.portal ？在什麼狀況下要用 [] 包起來？
另外，依照 @linzeyan  的解法也行，可是他的格式就跟 @tsengeagle 的不同？
```
hostvars[inventory_hostname]['groups']
hostvars[inventory_hostname].groups
```
然後為什麼 inventory_hostname 不必用 ' ' 包起來？

**Comment by tsengeagle** [comment]
msg可以，因為那是debug這個模組的參數
var則是ansible的關鍵字，例如下圖，把名稱叫做hello的variable帶給debug這個模組

這邊沒有定義hello
![default](https://user-images.githubusercontent.com/6193596/48388766-85ddf900-e735-11e8-9ce1-c6368c1e2f67.png)
這邊定義了hello的內容
![default](https://user-images.githubusercontent.com/6193596/48388755-7e1e5480-e735-11e8-894a-25e0c4ec5eea.png)

可以比較看看兩者的差異

**Comment by linzeyan** [comment]
var=hostvars[inventory_hostname]['groups']
msg={{ hostvars[inventory_hostname]['groups'] }}

**Comment by tsengeagle** [comment]
inventory_hostname也是一個variable
[文件](https://docs.ansible.com/ansible/2.7/user_guide/playbooks_variables.html#accessing-information-about-other-hosts-with-magic-variables)

**Comment by changchichung** [comment]
var/msg 的部份我了解了

那關於第二個問題，有解答嗎？
```
我要如何得知要用 "hostvars[inventory_hostname]" .groups.portal 這種格式，為什麼不是用 hostvars.inventory_hostname.groups.portal ？在什麼狀況下要用 [] 包起來？
另外，依照 @linzeyan 的解法也行，可是他的格式就跟 @tsengeagle 的不同？
hostvars[inventory_hostname]['groups']
hostvars[inventory_hostname].groups
```

**Comment by tsengeagle** [comment]
ansible的物件會以json的格式來呈現，對沒碰過的物件，我的學習途徑是這樣的

1. 先把這個物件印出來，以下圖為例，我們就可以知道，hostvars這個物件是兩個元素組成（綠色框的部分），這兩個元素分別是ErsServer及apl01，這兩個元素分別都有屬性（黃色框的內容）
![default](https://user-images.githubusercontent.com/6193596/48393178-7bc5f580-e749-11e8-90ef-c27a642bb61b.png)

2. 接著就是嘗試再取內部的資料出來，舉例，假設我要取ErsServer（第一個元素）的groups，用法就是 `hostvars.ErsServer.groups`，假設要取apl01的ap_environment，我就會用`hostvars.apl01.ap_environment`

3. 取值的方式，我是用json的原理去理解
`ansible apl01 -i inventories/lab -m debug -a "msg={{ hostvars.ErsServer }}"`
`ansible apl01 -i inventories/lab -m debug -a "msg={{ hostvars['ErsServer'] }}"`
這兩種方法都可以，第一行是把整個資料當作一個大物件，用屬性名稱的方式取，第二行則是把資料當作陣列，用陣列元素取。
我覺得當作陣列元素的方式比較有彈性，因為元素可以用字串帶值進去，也就是這個用法`hostvars[inventory_hostname].groups`

**Comment by zarr12steven** [comment]
> 我要如何得知要用 "hostvars[inventory_hostname]" .groups.portal 這種格式，為什麼不是用 hostvars.inventory_hostname.groups.portal ？在什麼狀況下要用 [] 包起來？ 另外，依照 @linzeyan 的解法也行，可是他的格式就跟 @tsengeagle 的不同？ hostvars[inventory_hostname]['groups'] hostvars[inventory_hostname].groups


其實這二種寫法都可以用，這樣的寫法主要是受到 PYTHON 取值的方式有所不同。
可以參考下列網址

* [列表的使用](https://ithelp.ithome.com.tw/articles/10185694)
* [字典的使用](https://ithelp.ithome.com.tw/articles/10186267)

但依照你提問，**`在什麼狀況下要用 [] 包起來？`** ，這我覺得純碎是看個人習慣，像我之前寫的時候，大都會是用這種寫法

```
{{ ansible_facts.eth0.ipv4.address }}
```

但後來就慢慢都統一寫成下面這種寫法

```
{{ ansible_facts["eth0"]["ipv4"]["address"] }}
```

Reference: 

* [Accessing complex variable data](https://docs.ansible.com/ansible/2.7/user_guide/playbooks_variables.html)


以上提供你參考，若有錯誤，還請多多指教了。

**Comment by changchichung** [comment]
感謝各位回覆，我會研究看看json 格式和還有語法

**Comment by tsengeagle** [comment]
> 感謝各位回覆，我會研究看看json 格式和還有語法

@zarr12steven 大大的說法比較精確

**Comment by chusiang** [comment]
Hi @changchichung,

待問題解決之後，記得關 ticket 喔。😉
