### ISSUE TITLE
Ubuntu 16.04 預設沒有安裝 Python2.x 的版本，要怎麼透過 Ansible 來安裝？

### ISSUE THREAD

**Issue by zarr12steven** [ansible-tw/AMA#4]
### ENVIORNMENT

```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```

### ISSUE

一開始要執行 `ansible all -m setup` 時，發現 `Ubuntu` 那台機器噴錯了，主要是說找不到 python，因為 `Ubuntu 16.04` 預設是安裝 `Python 3`，所以無法使用。

### FIXED

如果是 `Ubuntu 16.04` 目前的解法是自已手動先下 `ansible hostname or groupname -m raw -a "apt-get install python"`。

**Comment by zarr12steven** [comment]
### 補充：

#### Q:  凍仁大大問說為什麼用 `raw` 就可以去安裝 python，是因為沒用到 Python 嗎 ？

#### A： 簡單說就是官方說因為有些設備或機器預設沒有安裝 Python，所以就用 remote shell 的方式去執行指令。  原文參考如下 ↓↓↓

> Executes a low-down and dirty SSH command, not going through the module subsystem. This is useful and should only be done in two cases. The first case is installing python-simplejson on older (Python 2.4 and before) hosts that need it as a dependency to run modules, since nearly all core modules require it. Another is speaking to any devices such as routers that do not have any Python installed. In any other case, using the shell or command module is much more appropriate. Arguments given to raw are run directly through the configured remote shell. Standard output, error output and return code are returned when available. There is no change handler support for this module. This module does not require python on the remote system, much like the script module.

**Comment by chusiang** [comment]
Good job!

**Comment by chusiang** [comment]
來這邊補一下今日 survey 到的資訊：

- 前人的作法與以上差不多。
  - [Get Ansible to work on bare Ubuntu 16.04 without python 2.7](https://gist.github.com/gwillem/4ba393dceb55e5ae276a87300f6b8e6f)
- 在 Ansible 2.2 之後加入了 [Python 3 Support — Ansible Documentation](https://docs.ansible.com/ansible/python_3_support.html) 的 feature。
